# Generated by Django 5.1.4 on 2025-01-03 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpmn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bpmndiagram',
            name='bpmn_svg',
            field=models.TextField(blank=True, null=True),
        ),
    ]
