# Generated by Django 5.1.4 on 2025-01-19 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpmn', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BPMNTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('bpmn_xml', models.TextField()),
                ('bpmn_svg', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
