# Generated by Django 5.1.4 on 2026-09-15 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpmn', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bpmndiagram',
            name='encrypted_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='folder',
            name='encrypted_folder_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
