# Generated by Django 5.1.4 on 2025-01-23 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpmn', '0002_bpmntemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bpmntemplate',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('bot', 'Bot'), ('user', 'User')], max_length=50),
        ),
        migrations.CreateModel(
            name='DiagramVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField()),
                ('version_name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bpmn_xml', models.TextField()),
                ('diagram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='bpmn.bpmndiagram')),
            ],
            options={
                'unique_together': {('diagram', 'version_number')},
            },
        ),
    ]
