# Generated by Django 5.1.4 on 2025-01-04 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpmn', '0003_bpmnconversation_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bpmnconversation',
            name='bpmn',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bpmn.bpmndiagram'),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('bot', 'Bot'), ('user', 'User')], max_length=50),
        ),
    ]
