# Generated by Django 5.1.4 on 2025-01-26 03:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpmn', '0004_alter_bpmntemplate_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bpmndiagram',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diagrams', to='bpmn.folder'),
        ),
    ]
