# Generated by Django 5.1.4 on 2025-01-12 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpmn', '0004_alter_bpmnconversation_bpmn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bpmndiagram',
            name='privacy',
            field=models.CharField(choices=[('public', 'Public'), ('restricted', 'Restricted')], default='restricted', max_length=10),
        ),
        migrations.AlterField(
            model_name='diagramshare',
            name='permission',
            field=models.CharField(choices=[('viewer', 'Viewer'), ('editor', 'Editor'), ('commenter', 'Commenter')], default='viewer', help_text='Permission level for the shared user.', max_length=10),
        ),
    ]
