# Generated by Django 5.1.4 on 2025-01-26 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpmn', '0005_bpmndiagram_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='encrypted_folder_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('bot', 'Bot'), ('user', 'User')], max_length=50),
        ),
    ]
