# Generated by Django 5.1.4 on 2025-01-12 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpmn', '0005_alter_bpmndiagram_privacy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('user', 'User'), ('bot', 'Bot')], max_length=50),
        ),
    ]
