# Generated by Django 5.1.4 on 2025-01-25 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bpmn', '0003_alter_bpmntemplate_description_and_more'),
        ('bpmn', '0006_alter_message_message_type'),
    ]

    operations = [
    ]
