# Generated by Django 5.1.4 on 2024-12-07 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('specialization', models.CharField(max_length=100)),
                ('qualification', models.TextField()),
                ('experience_years', models.PositiveIntegerField()),
                ('bio', models.TextField(blank=True, null=True)),
                ('clinic_name', models.CharField(max_length=200)),
                ('clinic_address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=20)),
                ('working_days', models.JSONField(default=list)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('break_times', models.JSONField(blank=True, default=list, null=True)),
                ('appointments_per_slot', models.PositiveIntegerField(default=1)),
                ('slot_duration', models.PositiveIntegerField(default=30)),
                ('booking_window', models.PositiveIntegerField(default=30)),
                ('cancellation_policy', models.TextField(blank=True, null=True)),
                ('languages_spoken', models.JSONField(blank=True, default=list, null=True)),
                ('consultation_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_methods', models.JSONField(blank=True, default=list, null=True)),
            ],
        ),
    ]
