# Generated by Django 5.1.4 on 2024-12-08 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment_chatbot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='appointments_per_slot',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='booking_window',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='cancellation_policy',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='consultation_fee',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='payment_methods',
        ),
    ]
