# Generated by Django 5.1.4 on 2024-12-08 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment_chatbot', '0004_alter_doctor_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='qualification',
        ),
    ]
