# Generated by Django 5.1.4 on 2024-12-08 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment_chatbot', '0005_remove_doctor_qualification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='gender',
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('slot', models.CharField(max_length=20)),
                ('patient_name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Booked', 'Booked'), ('Cancelled', 'Cancelled')], default='Booked', max_length=20)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='appointment_chatbot.doctor')),
            ],
        ),
    ]
