# Generated by Django 5.1.4 on 2024-12-08 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment_chatbot', '0006_remove_doctor_gender_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True),
        ),
    ]
