# Generated by Django 5.1.4 on 2024-12-08 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment_chatbot', '0007_doctor_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='patient_contact',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='symptoms',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('Booked', 'Booked'), ('Cancelled', 'Cancelled'), ('Completed', 'Completed')], default='Booked', max_length=20),
        ),
    ]
