# Generated by Django 5.1.4 on 2024-12-08 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment_chatbot', '0008_appointment_patient_contact_appointment_symptoms_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='break_times',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='city',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='experience_years',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='languages_spoken',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='slot_duration',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='working_days',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='zip_code',
        ),
        migrations.AddField(
            model_name='doctor',
            name='available_time_slots',
            field=models.JSONField(blank=True, default=dict, help_text="Doctor's available time slots in JSON format"),
        ),
    ]
