# Generated by Django 5.1.4 on 2024-12-08 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment_chatbot', '0009_remove_doctor_bio_remove_doctor_break_times_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonaInstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persona', models.CharField(max_length=100, unique=True)),
                ('instruction', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='doctor',
            name='available_time_slots',
            field=models.JSONField(blank=True, default=dict, help_text='Doctor\'s available time slots in JSON format(eg: {\n    "2024-12-06": ["10:00 AM", "11:00 AM", "2:00 PM"],\n    "2024-12-07": ["9:00 AM", "1:00 PM", "3:00 PM"]\n})'),
        ),
    ]
